### PR TITLE
Oom alloc

### LINKED ISSUE #550: Bug: Out of memory error caused by over-allocation in cfb.rs Sectors::get_chain() parsing
### Current behavior

#529 added a testcase that triggers an OOM allocation. Currently Rust still treats allocator failures as aborts unless nightly features are used to override this behavior.

As a contributor to [rust-cfb](https://github.com/mdsteele/rust-cfb) that has run through TBs of data in production and never had an abort or panic, we might want to consider using it as a replacement to the current code.
Because CFB is used across .doc, .ppt, .xls and .msg files, it is likely it is better tested. It has ~5x the downloads of calamine.

### Expected behavior

No aborts and no panics.

### Sample code to reproduce

```rust
See #529
```

### Test file

See #529 

### Environment

```text

```

### Checklist

- [x] I have added a complete sample program that compiles in Rust.
- [x] I have added a test file.

### PR DESCRIPTION
**Pull request by sftse**
New PR for #529. Fixes #550 

We can bound sector numbers based on the file size. If we try to access one beyond the end, we error. This prevents the OOM because the in memory buffer gets extended up to the offset of the file where the sector would presumably be. Large sector numbers translate to offsets, triggering the OOM.

### CODE REVIEW

File: src/cfb.rs [hunk 1]
```diff
@@ -279,6 +279,7 @@ impl Sectors {
             Vec::new()
         };
         while sector_id != ENDOFCHAIN {
+            // FIXME: see tests/OOM_alloc3.xls, this call OOMs
```
Comment (jmcnamara) [inline src/cfb.rs]: I think the changes in this commit should be merged with the next commit.

File: src/cfb.rs [hunk 2]
```diff
@@ -78,7 +80,9 @@ impl Cfb {
     pub fn new<R: Read>(mut reader: &mut R, len: usize) -> Result<Cfb, CfbError> {
         // load header
         let (h, mut difat) = Header::from_reader(&mut reader)?;
-        let mut sectors = Sectors::new(h.sector_size, Vec::with_capacity(len));
+        assert_ne!(h.sector_size, 0);
+        let maxid = len / h.sector_size;
+        let mut sectors = Sectors::new(h.sector_size, Vec::with_capacity(len), maxid as u32);
```
Comment (jmcnamara) [inline src/cfb.rs]: Wouldn't it be simpler to just use a fixed size for capacity like `Vec::with_capacity(1024)` here and elsewhere. I doubt that these are cases where over or under allocation of Vec will make any difference to performance.

File: src/cfb.rs [hunk 3]
```diff
@@ -78,7 +80,9 @@ impl Cfb {
     pub fn new<R: Read>(mut reader: &mut R, len: usize) -> Result<Cfb, CfbError> {
         // load header
         let (h, mut difat) = Header::from_reader(&mut reader)?;
-        let mut sectors = Sectors::new(h.sector_size, Vec::with_capacity(len));
+        assert_ne!(h.sector_size, 0);
```
Comment (jmcnamara) [inline src/cfb.rs]: Replace this assert with an error Result.

Comment (sftse) [reply src/cfb.rs]: The intent was a bit unclear, I've cleaned that up. It can't be zero because of the validation done in `Header::from_reader`.

File: src/cfb.rs (hunk 1 above)
Comment (jmcnamara) [reply src/cfb.rs]: > The separate commit adding the test case is useful to verify the abort before verifying the fix.

In general it is best not to commit any changes that break the build process or the test suite since it makes running `git bisect` harder. I've worked on projects where both of these are strictly forbidden. So the test case should be rolled into the commit that fixes it.

File: tests/test.rs [hunk 4]
```diff
@@ -17,12 +17,16 @@ use std::sync::Once;
 
 static INIT: Once = Once::new();
 
+fn test_path(name: &str) -> std::string::String {
```
Comment (jmcnamara) [inline tests/test.rs]: +1. This is a good change cleanup change.

I don't think the `env!("CARGO_MANIFEST_DIR")` is strictly required. I leave it out of some of the sample code. The test suite will definitely run without it. I don't know what cases, historically or otherwise, required it. Maybe you could consider dropping it here and just using `format!("tests/{name}")`.

File: tests/test.rs [hunk 5]
```diff
@@ -2201,6 +2201,9 @@ fn test_oom_allocation() {
     let ws = xls.worksheets();
     assert_eq!(ws.len(), 1);
     assert_eq!(ws[0].0, "Colsale (Aug".to_string());
+
+    let path = test_path("OOM_alloc3.xls");
```
Comment (jmcnamara) [inline tests/test.rs]: Same comment as the higher level conversation: failing test cases should be merged with the commit that fixes them.

**Comment by sftse** [comment]
In terms of merging policy, for me there are two independent axes: a) Should one rebase so that the resulting merge is 'trivial' and b) should the resulting merge commit be kept around. I'm strongly in favor of a) but don't have strong for/against on b), leaning slightly in favor of keeping the commits because the PRs then get referenced that caused the commits, discussion is easier to find.

**Comment by sftse** [comment]
@jmcnamara Do you think we can merge without blocking on a decision on merge policy?
